server:
  port: 8088
logging:
  level:
    '[org.springframework.web]': debug
    '[org.mybatis]': debug
    '[org.mariadb.jdbc.client.impl]': debug
    '[org.springframework.data.redis]': debug
    '[io.lettuce.core]': debug