spring:
  application:
    name: university-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/web
    username: beyond
    password: beyond
  # Redis 연결을 위한 설정
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
    type-aliases-package: com.beyond.university.*.model.vo
    mapper-locations:
      - classpath:mappers/**/*.xml
    configuration:
      jdbc-type-for-null: NULL
springdoc:
  swagger-ui:
    operations-sorter: method
  paths-to-match:
  - /api/v1/**
springboot:
  jwt:
    secret: h1o2n3gg5i6l7d8o9n0g;h1o2n3gg5i6l7d8o9n0g